"""
What this build was provisioned with when it was packaged.

Some of what an installation runs on is neither the customer's to choose
nor sensible to ask them for. The outgoing mail account is the clearest
case: "Forgot password" has to email a temporary password from
*somewhere*, and a shop that bought a printing ERP has no mail server,
no reason to have one, and no way to be walked through configuring one
over the phone. So the vendor's own account is decided once, at build
time, and travels inside the executable.

This file is generated by `scripts/provision_build.py` during the
PyInstaller run and bundled into the build. It is vendor material in the
same sense as `infrastructure/licensing/public_keys.py` — it says what
this build *is*, not how a machine was set up — and it is the only thing
this application ships that is read from inside the bundle rather than
from the customer's own folders.

It sits below the customer's `config/settings.json` in
`app.config.settings`, so a shop that does have its own mail server can
still override every value in it without a new build.

**On the one secret in here.** The mail account's password is in this
file, and this file is inside the executable. The contents are encrypted
with a key derived in the code below — which means the key is in the same
binary, which means this is not secrecy. It is there so that the password
cannot be scraped out of the install folder with `strings.exe` or a text
search, and nothing more. What actually limits the damage is the nature
of the account: it exists only to send this one message, it is worth
rotating on a schedule, and rotating it is a change to `.env.build` and a
rebuild.

That is a real step down from "every secret lives in the OS credential
vault", which is where this application keeps everything else. It buys
the one thing the vault cannot give a shipped build: a password reset
that works on a machine nobody has visited. The vault still wins where it
has an entry — see `infrastructure/notifications/smtp_email_sender.py`.

Nothing here raises, for the same reason `runtime_config.py` does not: a
build that was packaged wrong is a bad afternoon for whoever packaged it,
not a reason a shop cannot invoice. A missing or unreadable bundle reads
as empty and the mail feature is simply off.
"""
from __future__ import annotations

import base64
import hashlib
import json
import logging
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from cryptography.fernet import Fernet, InvalidToken

from app.config.paths import PROVISIONING_PATH

logger = logging.getLogger(__name__)

_EMPTY: Mapping[str, Any] = {}

SECRETS_SECTION = "secrets"
"""The block secrets are filed under. Everything outside it is ordinary
configuration and is read by `app.config.settings` like any other source."""

_KEY_MATERIAL = b"ChandGraphicsERP/provisioning/v1"
"""Changing this makes every bundle already produced unreadable, which is
only ever what you want alongside a rebuild. Versioned so that a future
format change has somewhere to go."""


def _key() -> bytes:
    """Fernet wants 32 bytes, url-safe base64 encoded."""
    return base64.urlsafe_b64encode(hashlib.sha256(_KEY_MATERIAL).digest())


# --------------------------------------------------------------- write


def encode_provisioning(bundle: Mapping[str, Any]) -> bytes:
    """Encode a bundle for packaging. Used by the build, not by the app.

    Kept here beside the reader on purpose: a format written in one file
    and parsed in another is a format that drifts, and the failure shows
    up in a shipped installer rather than in a test.
    """
    return Fernet(_key()).encrypt(json.dumps(bundle).encode("utf-8"))


# ---------------------------------------------------------------- read


def _read(path: Path) -> Mapping[str, Any]:
    if not path.exists():
        # The ordinary case in a development checkout, and in a build made
        # with ALLOW_UNPROVISIONED_BUILD. Not worth a log line.
        return _EMPTY

    try:
        decoded = Fernet(_key()).decrypt(path.read_bytes())
    except (OSError, InvalidToken):
        # Truncated, corrupted, or produced by a build whose key material
        # has since changed. All three mean the same thing to us.
        logger.warning("Provisioning bundle at %s is unreadable; ignoring it", path)
        return _EMPTY

    try:
        loaded = json.loads(decoded.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        logger.warning("Provisioning bundle at %s is not readable JSON; ignoring it", path)
        return _EMPTY

    if not isinstance(loaded, dict):
        logger.warning("Provisioning bundle at %s is not a JSON object; ignoring it", path)
        return _EMPTY

    return loaded


_bundle: Mapping[str, Any] | None = None


def _cached() -> Mapping[str, Any]:
    """Read once per process.

    The bundle is inside the executable, so it cannot change while the
    application runs, and `provisioned_secret` is called on every send.
    """
    global _bundle
    if _bundle is None:
        _bundle = _read(PROVISIONING_PATH)
    return _bundle


def load_provisioning() -> Mapping[str, Any]:
    """The configuration this build was packaged with, secrets excluded.

    Shaped like `config/settings.json` so that `app.config.settings` can
    read both through the same `section()` helper.
    """
    return {name: block for name, block in _cached().items() if name != SECRETS_SECTION}


def provisioned_secret(key: str) -> str | None:
    """One secret from the bundle, or `None` if this build carries none.

    Asked for at the moment it is used, never held — the same discipline
    `SecretVault` is used with, and for the same reason: a secret that is
    not in a long-lived object is not in a crash dump either.
    """
    secrets = _cached().get(SECRETS_SECTION)
    if not isinstance(secrets, dict):
        return None
    value = secrets.get(key)
    return value if isinstance(value, str) and value else None


def reset_cache() -> None:
    """Forget the bundle read so far. For tests, which write their own."""
    global _bundle
    _bundle = None
